name: "Publish main to FlakeHub"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "FlakeHub version to publish"
        type: "string"
        required: true

jobs:
  flakehub-publish:
    runs-on: "ubuntu-latest"

    permissions:
      id-token: "write"
      contents: "read"

    steps:
      - uses: "actions/checkout@v6"
        with:
          persist-credentials: false
          ref: "main"

      - uses: "DeterminateSystems/determinate-nix-action@v3"

      - uses: "DeterminateSystems/flakehub-push@main"
        with:
          visibility: "public"
          name: "torstenboettjer/rescile-ce-flake"
          tag: "${{ inputs.tag }}"
          include-output-paths: true
